Telemetry remove
ploomber/soopervisor pull request #101
Opened 2022-08-01 19:03 UTC by Wxl19980214

## Describe your changes

Use ploomber_core.telemetry 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-08-15 19:30 UTC, idomic commented
@Wxl19980214 is this ready for review?
Please resolve conflicts

2022-08-15 21:22 UTC, idomic commented
@Wxl19980214 ready for review? If so, please fix the conflict

2022-08-17 04:54 UTC, edublancas requested changes

2022-08-17 04:54 UTC, edublancas commented on setup.py
> +    'ploomber_core',
```suggestion
    'ploomber-core',
```
that's the right name of the package. I was surprised that this works as well! TIL pip replaces the `_` with `-`, that's why it didn't break

2022-08-17 04:54 UTC, edublancas commented on src/soopervisor/cli.py
> +from soopervisor import __version__ as ver
```suggestion
from soopervisor import __version__
```

no need to rename here

2022-08-17 04:54 UTC, edublancas commented on src/soopervisor/cli.py
> +@click.version_option(version=ver)
```suggestion
@click.version_option(version=__version__)
```
no need to rename

2022-08-17 04:54 UTC, edublancas commented on src/soopervisor/cli.py
> +telemetry = Telemetry(api_key, ver, 'soopervisor')
please create a `soopervisor.telemetry` module and instantiate this there. also move the posthog key to that file. same thing as we did with ploomber

2022-08-17 15:41 UTC, Wxl19980214 commented on src/soopervisor/cli.py
> +telemetry = Telemetry(api_key, ver, 'soopervisor')
Ok

2022-08-17 19:23 UTC, Wxl19980214 commented
ready for merge

2022-08-17 19:57 UTC, edublancas approved these changes

2022-08-17 19:58 UTC, merged

2022-08-17 19:59 UTC, idomic commented
@Wxl19980214 Nice job!