Add environment vars expansion and pre defined git hashes in the yaml
ploomber/soopervisor pull request #120
Opened 2022-11-03 23:03 UTC by feribg

## Describe your changes

## Issue ticket number and link
Closes #116

## Checklist before requesting a review
- [ x  ] I have performed a self-review of my code
- [ x ] I have added thorough tests (when necessary).
- [  ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-11-05 18:39 UTC, edublancas requested changes

2022-11-05 18:39 UTC, edublancas commented on tests/test_commons_docker.py
> +    expected = ('env.yaml\nenvironment.yml\nfast-pipeline.tar.gz\n'
can you add two more tests?

let's check the content of the env.yaml, one when a user already has one (then the content should be the existing user values + the default ones) and another one when there is no user env.yaml  and we create it

2022-11-06 00:37 UTC, feribg commented on tests/test_commons_docker.py
> +    expected = ('env.yaml\nenvironment.yml\nfast-pipeline.tar.gz\n'
Yes but can you please share some thoughts on how these test projects are created, it doesnt seem any of them uses a git repo etc ?

2022-11-22 21:02 UTC, feribg commented on tests/test_commons_docker.py
> +    env_contents = out.stdout.decode()
@edublancas this file only has `{}` as contents instead it should have `build_time` and the git placeholders it does have the build time locally pre sending to docker and not the placeholders but im kinda lost in all the indirection where is that stuff being injected / cleared.

2022-12-29 04:04 UTC, edublancas approved these changes

2022-12-29 04:04 UTC, merged

2022-12-29 04:05 UTC, edublancas commented
hey @feribg, I fixed and merged the PR. Please take the version in master for a spin and let me know if it works for you. If so, I'll make a release.

Note: I saw you had a `build_time` placeholder (apart from the git ones) in your logic, I deleted it because I believe that will never get executed as it is not defined as a default placeholder in ploomber. is that right?

2022-12-29 14:57 UTC, feribg commented
@edublancas thanks i will take a look and try to use the master one and report back. Yes I just added that one but didnt end up implementing it the idea being is to act as a git hash if it's a git repo but I dont really need it, figured it might be useful.

2022-12-29 14:58 UTC, edublancas commented
great, I also released a new ploomber version that contains [your changes](https://github.com/ploomber/ploomber/blob/master/CHANGELOG.md#0218-2022-12-27).

2023-03-22 22:18 UTC, feribg commented
@edublancas  doesn't look like its working correctly. 

[`env_default = EnvDict({}, path_to_here=Path(path_to_env).parent)`](https://github.com/ploomber/soopervisor/blob/69963e83a8515ba1f6d6c5b9c3a1db2ec530195c/src/soopervisor/commons/docker.py#L98)

```* {{git_hash}}: Ensure git is installed and git repository exists```

```>>> import soopervisor
>>> soopervisor.__version__
'0.9.1'```

Seems like it keeps looking for .git for whatever reason and its a bit tricky to debug it in AWS batch.

2023-03-30 04:24 UTC, edublancas commented
Since ploomber implements the logic for expanding these values, it's possible to replicate this exclusively with ploomber, right? No AWS Batch, no docker.

Based on the error message, looks like there is a bug that's erroring because there is no repository, so probably we need to add some extra logic to ploomber that checks if those placeholders are defined already and skip checking for a git repository. Do you have time to submit a PR?