Kubeflow connector
ploomber/soopervisor pull request #35
Opened 2022-01-03 13:35 UTC by idomic

2022-01-03 17:16 UTC, edublancas commented on src/soopervisor/commons/docker.py
> +    # _validate_repository(cfg.repository)
@idomic

2022-01-03 22:28 UTC, idomic commented on tests/assets/my_project/setup.py
> +    install_requires=['pandas', 'ploomber==0.13.6', 'build'],
TODO remove version lock once stable

2022-01-05 18:27 UTC, idomic commented
@edublancas looks like it'll pass, wanna start the review?

2022-01-11 01:41 UTC, edublancas requested changes

2022-01-11 01:41 UTC, edublancas commented on src/soopervisor/commons/dag.py
> +    spec, relative_path = find_spec(cmdr=cmdr, name=name)
spec isn't used here, and find_spec is called in load_dag. maybe it's better to have `load_dag` to also return `relative_path`, this way we'll only call `find_spec` once

2022-01-11 01:41 UTC, edublancas commented on src/soopervisor/commons/docker.py
> +        image_target = cfg.repository
is this to allow the user set the version from the soopervisor.yaml file?

2022-01-11 01:41 UTC, edublancas commented on src/soopervisor/kubeflow/export.py
> +            args.append('        - {outputPath: product}\n')
it'd be easier to create the spec as a Python dictionary and serialize it as a YAML file at the end, as we do with Argo. Otherwise, we risk producing invalid YAML files

2022-01-11 01:41 UTC, edublancas commented on tests/airflow/test_airflow_export.py
> +    assert {t.image for t in td.values()} == {'image_target:latest'}
why did this change? did the default value change?

2022-01-11 01:41 UTC, edublancas commented on tests/kubeflow/test_kubeflow_export.py
> +# @pytest.mark.parametrize('mode, args', [['incremental', '']],
please remove the commented code

2022-01-16 15:15 UTC, idomic commented on src/soopervisor/commons/docker.py
> +        image_target = cfg.repository
Yes, in addition it allowed me to pass a remote repo, for instance, idomic/general:ml-intermidiate-latest3

2022-01-16 15:16 UTC, idomic commented on tests/airflow/test_airflow_export.py
> +    assert {t.image for t in td.values()} == {'image_target:latest'}
Yeah when I pulled from master it change, and then I had to change the tests

2022-01-16 15:25 UTC, idomic commented on src/soopervisor/commons/dag.py
> +    spec, relative_path = find_spec(cmdr=cmdr, name=name)
Good idea! fixed.

2022-01-17 02:49 UTC, edublancas commented
is this ready for review?

2022-01-17 04:29 UTC, idomic commented
Yes

On Sun, Jan 16, 2022, 9:49 PM Eduardo Blancas ***@***.***>
wrote:

> is this ready for review?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ploomber/soopervisor/pull/35#issuecomment-1014088834>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYPJOJTNI62SK3OAQTFVIDUWN7UBANCNFSM5LFHZZWA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-18 04:18 UTC, edublancas requested changes

2022-01-18 04:18 UTC, edublancas commented on doc/tutorials/kubeflow.rst
> +.. note:: **The Kubeflow tutorial is in beta! Got questions or found issues?** Reach out to us on `Slack <https://ploomber.io/community/>`_.
maybe say the "kubeflow integration"?

2022-01-18 04:18 UTC, edublancas commented on doc/tutorials/slurm.rst
> +    # Install miniconda (to get a Python environment ready, not needed if
haha what's wrong with the lowercase? i never use uppercase in code comments

2022-01-18 04:18 UTC, edublancas commented on src/soopervisor/commons/docker.py
> +        image_target = cfg.repository
but the part after `:` is only for the tag, right? with the old version you could still point to a remote repo

2022-01-18 04:18 UTC, edublancas commented on src/soopervisor/commons/docker.py
> +            image_target = f'image_target:{version}'
i think here we should add a `e.print(f'No tag found in soopervisor.yaml, using default value: {version}')` so the user knows that since they didn't provide a value, we'll use a default

2022-01-18 04:18 UTC, edublancas commented on src/soopervisor/commons/docker.py
> +            image_target = f'image_target:{version}'
also, please add an entry to the changelog explaining this

2022-01-18 04:18 UTC, edublancas commented on src/soopervisor/kubeflow/export.py
> +            print("Generating kubeflow script")
please use click.echo instead of print

2022-01-18 04:18 UTC, edublancas commented on src/soopervisor/commons/docker.py
> +            image_target = f'image_target:{version}'
there's an error here, you're missing the `{}`, it should be `image_target = f'{image_target}:version}'` - you need to update the airflow export test as well

2022-01-18 04:18 UTC, edublancas commented on tests/airflow/test_airflow_export.py
> +    assert {t.image for t in td.values()} == {'image_target:latest'}
see my comment above, this needs to revert to the old value

2022-01-18 04:18 UTC, edublancas commented on tests/argo/test_argo_export.py
> +        'image'] == 'image_target:0.1dev'
same here, revert to old value

2022-01-28 03:36 UTC, edublancas commented
can you rebase this branch? it has conflicts with master

2022-01-29 05:28 UTC, merged