Airflow example change
ploomber/soopervisor pull request #54
Opened 2022-01-20 11:55 UTC by idomic

@edublancas check it out, added a fix on top of the docker file tested with and without a ~/.ploomber home dir.

2022-01-20 19:04 UTC, edublancas commented
this is failing because it depends on the unreleased ploomber version right?

2022-01-20 20:44 UTC, idomic commented
Yeah reran it, I wasn't sure how to incorporate Slurm and Lambda

2022-01-21 00:38 UTC, edublancas requested changes

2022-01-21 00:38 UTC, edublancas commented on src/soopervisor/cli.py
> +        raise e
here it should only be `except Exception`  and  `raise`

2022-01-21 00:38 UTC, edublancas commented on src/soopervisor/cli.py
> +        raise e
here it should only be `except Exception`  and  `raise`

2022-01-21 00:38 UTC, edublancas commented on tests/conftest.py
> +def ignore_ploomber_stats_enabled_env_var(monkeypatch):
we don't need these fixtures. the one we need is the one with the autouse=true that prevents posthog calls

2022-01-21 00:38 UTC, edublancas commented on tests/test_cli.py
> +def test_check_stats_enabled(ignore_env_var_and_set_tmp_default_home_dir):
we don't need this test

2022-01-21 00:38 UTC, edublancas commented on tests/test_cli.py
> +    stats_mock.call_count == 3
why are we testing call_count is three?

2022-01-21 00:38 UTC, edublancas commented on src/soopervisor/cli.py
> +                shutil.copytree(home_path, path_out)
let's move this logic to docker.commons, since this is not applicable to all backends (only docker-based ones). then add unit test in test_cli.py that after running the export command, the content of ~/.ploomber is copied

2022-01-21 14:44 UTC, idomic commented on src/soopervisor/cli.py
> +        raise e
How would we know the error?

2022-01-21 14:52 UTC, idomic commented on tests/test_cli.py
> +    stats_mock.call_count == 3
Making sure it was actually called as part of the add export flow?

2022-01-21 14:55 UTC, idomic commented on src/soopervisor/cli.py
> +                shutil.copytree(home_path, path_out)
In the build function?

2022-01-23 23:32 UTC, idomic commented
@edublancas any updates on this?

2022-01-24 20:50 UTC, edublancas requested changes

2022-01-24 20:50 UTC, edublancas commented on tests/test_cli.py
> +    assert conf.exists()
we need to test that the files are inside the tar.gz file since that's what we copy to the docker container

2022-01-24 20:51 UTC, edublancas commented
also, since this depends on a newer ploomber version, this needs updates: https://github.com/ploomber/soopervisor/blob/2d6315baa34703692f768d9067808dcafcc41943/setup.py#L32

for version `>=0.14.6`

2022-01-25 22:03 UTC, idomic commented on tests/test_cli.py
> +    assert conf.exists()
Fixed issues

2022-01-28 03:34 UTC, edublancas approved these changes

2022-01-28 03:35 UTC, merged