multiple requirements.txt files (Work in progress)
ploomber/soopervisor pull request #86
Opened 2022-06-19 08:34 UTC by neelasha23

## Describe your changes

## Issue ticket number and link
Closes #x 

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-06-19 14:27 UTC, neelasha23 commented
I would need some help here. I'm almost done with the code and test cases. There are some existing test cases which are failing and I cannot get to the root cause even after debugging. 
1. Testcases for airflow export: `test_airflow_export_sample_project` and `test_export_airflow_callables` with the below error

```
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x16ee15310>, mock_docker_calls_callables = <ploomber.io._commander_tester.CommanderTester object at 0x16ee152b0>
tmp_callables = PosixPath('/private/var/folders/ff/jydfr9497jn4lqn28913mvwc0000gn/T/pytest-of-neelashasen/pytest-216/test_export_airflow_callables_2/assets/callables'), no_sys_modules_cache = None
skip_repo_validation = None, mode = 'force', args = ' --force'

    @pytest.mark.parametrize('mode, args', [
        ['incremental', ''],
        ['regular', ''],
        ['force', ' --force'],
    ],
                             ids=['incremental', 'regular', 'force'])
    def test_export_airflow_callables(monkeypatch, mock_docker_calls_callables,
                                      tmp_callables, no_sys_modules_cache,
                                      skip_repo_validation, mode, args):
        exporter = AirflowExporter.new(path_to_config='soopervisor.yaml',
                                       env_name='serve')
    
        # this requires a git repo
        git_init()
    
        exporter.add()
        exporter.export(mode=mode)
    
        monkeypatch.syspath_prepend(Path('serve').resolve())
    
>       mod = importlib.import_module('callables')

/Users/neelashasen/Dev/soopervisor/tests/airflow/test_airflow_export.py:151: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/neelashasen/miniconda3/envs/soopervisor/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1030: in _gcd_import
    ???
<frozen importlib._bootstrap>:1007: in _find_and_load
    ???
<frozen importlib._bootstrap>:986: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:680: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:850: in exec_module
    ???
<frozen importlib._bootstrap>:228: in _call_with_frames_removed
    ???
/private/var/folders/ff/jydfr9497jn4lqn28913mvwc0000gn/T/pytest-of-neelashasen/pytest-216/test_export_airflow_callables_2/assets/callables/serve/callables.py:21: in <module>
    spec = json.loads(path_to_spec.read_text())
/Users/neelashasen/miniconda3/envs/soopervisor/lib/python3.9/pathlib.py:1266: in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
/Users/neelashasen/miniconda3/envs/soopervisor/lib/python3.9/pathlib.py:1252: in open
    return io.open(self, mode, buffering, encoding, errors, newline,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = PosixPath('/private/var/folders/ff/jydfr9497jn4lqn28913mvwc0000gn/T/pytest-of-neelashasen/pytest-216/test_export_airflow_callables_2/assets/callables/serve/callables.json')
name = '/private/var/folders/ff/jydfr9497jn4lqn28913mvwc0000gn/T/pytest-of-neelashasen/pytest-216/test_export_airflow_callables_2/assets/callables/serve/callables.json', flags = 16777216, mode = 438

    def _opener(self, name, flags, mode=0o666):
        # A stub for the opener argument to built-in open()
>       return self._accessor.open(self, flags, mode)
E       FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/ff/jydfr9497jn4lqn28913mvwc0000gn/T/pytest-of-neelashasen/pytest-216/test_export_airflow_callables_2/assets/callables/serve/callables.json'

/Users/neelashasen/miniconda3/envs/soopervisor/lib/python3.9/pathlib.py:1120: FileNotFoundError
```

2. Test cases for argo export :`test_export`, `test_custom_volumes`, `test_export_with_null_repository`

```
mock_docker_my_project = <ploomber.io._commander_tester.CommanderTester object at 0x177b9d460>, backup_packaged_project = None, skip_repo_validation = None
capsys = <_pytest.capture.CaptureFixture object at 0x177b9da90>

    def test_export_with_null_repository(mock_docker_my_project,
                                         backup_packaged_project,
                                         skip_repo_validation, capsys):
        exporter = ArgoWorkflowsExporter.new(path_to_config='soopervisor.yaml',
                                             env_name='serve')
        exporter.add()
    
        # set empty repository
        spec = yaml.safe_load(Path('soopervisor.yaml').read_text())
        spec['serve']['repository'] = None
        Path('soopervisor.yaml').write_text(yaml.safe_dump(spec))
    
        # reload exporter
>       ArgoWorkflowsExporter.load(path_to_config='soopervisor.yaml',
                                   env_name='serve').export(mode='incremental',
                                                            until=None)

/Users/neelashasen/Dev/soopervisor/tests/argo/test_argo_export.py:140: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/neelashasen/Dev/soopervisor/src/soopervisor/abc.py:340: in export
    return self._export(cfg=self._cfg,
/Users/neelashasen/Dev/soopervisor/src/soopervisor/argo/export.py:64: in _export
    pkg_name, target_image = docker.build(cmdr,
/Users/neelashasen/Dev/soopervisor/src/soopervisor/commons/docker.py:193: in build
    image = build_image(e,
/Users/neelashasen/Dev/soopervisor/src/soopervisor/commons/docker.py:95: in build_image
    e.run('docker',
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ploomber.io._commander.Commander object at 0x1612f64f0>, description = 'Testing File client', capture_output = True, expected_output = 'True\n', error_message = 'Missing File client'

    def run(self,
            *cmd,
            description=None,
            capture_output=False,
            expected_output=None,
            error_message=None,
            hint=None,
            show_cmd=True):
        """Execute a command in a subprocess
    
        Parameters
        ----------
        *cmd
            Command to execute
    
        description: str, default=None
            Label to display before executing the command
    
        capture_output: bool, default=False
            Captures output, otherwise prints to standard output and standard
            error
    
        expected_output: str, default=None
            Raises a RuntimeError if the output is different than this value.
            Only valid when capture_output=True
    
        error_message: str, default=None
            Error to display when expected_output does not match. If None,
            a generic message is shown
    
        hint: str, default=None
            An optional string to show when at the end of the error when
            the expected_output does not match. Used to hint the user how
            to fix the problem
    
        show_cmd : bool, default=True
            Whether to display the command next to the description
            (and error message if it fails) or not. Only valid when
            description is not None
        """
        cmd_str = ' '.join(cmd)
    
        if expected_output is not None and not capture_output:
            raise RuntimeError('capture_output must be True when '
                               'expected_output is not None')
    
        if description:
            header = f'{description}: {cmd_str}' if sh [...]

2022-06-20 13:45 UTC, neelasha23 commented
I also see this error in the Windows CI:
```
Checking out the ref
  "C:\Program Files\Git\bin\git.exe" checkout --progress --force refs/remotes/pull/86/merge
  Error: error: invalid path 'tests/assets/multiple_requirements_project/requirements.clean-*.lock.txt'
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128
```

The repo checkout itself is failing because of this file `tests/assets/multiple_requirements_project/requirements.clean-*.lock.txt`. Probably because we can't have `*` in filename on Windows?

2022-06-20 16:10 UTC, idomic commented
@neelasha23 Maybe we can try double underscore as well for windows? __

2022-06-20 16:33 UTC, neelasha23 commented
There is an issue that I'm facing with the airflow tests. The `tests/airflow/test_airflow_export.py ` cases kept failing because the mock was expecting `pkg-name.json` file inside `env-name` folder for non bash presets (I'm not sure why this happened because I have hardly changed anything in the conftest). So just to see if the test case is passing I changed this line  

https://github.com/ploomber/soopervisor/blob/81d0bda8879980b86c75aafcd4d68facf2130423/src/soopervisor/airflow/export.py#L98

However now the current CI error comes up `FAILED tests/test_export.py::test_checks_the_right_spec_pkg[AirflowExporter] - FileNotFoundError: [Errno 2] No such file or directory: 'serve/my_project.json'` .

I would need some help in understanding this functionality.

2022-06-20 17:41 UTC, idomic commented
@neelasha23 this code takes the final Airflow dag and saving it into the file the users can deploy with.
We're opening and writing into the json file, I don't think removing this line will suffice since the whole test is checking this export functionality. @edublancas thoughts?

2022-06-21 02:19 UTC, neelasha23 commented
Just to clarify, I haven't removed that line. Previously it was writing to pkgname.json I have only modified it to write to envname/ pkgname.json, because that's what the test case is suddenly expecting.  I'm not sure how this happened because I haven't made any major changes in the airflow pipeline.

2022-06-21 08:56 UTC, edublancas commented
ok, I found the issue. I pushed a commit changing this line:

https://github.com/ploomber/soopervisor/blob/81d0bda8879980b86c75aafcd4d68facf2130423/src/soopervisor/airflow/export.py#L98

to:

```python
path_dag_dict_out = Path(pkg_name + '.json')
```

since that's what I saw in the master branch.

then I saw a bunch of tests fail.

the problem is here: 

https://github.com/ploomber/soopervisor/blob/81d0bda8879980b86c75aafcd4d68facf2130423/src/soopervisor/commons/docker.py#L245

this line will behave differently depending on what happens with the for loop. If `lock_paths` is empty, it will never execute, if there are 1,2,3 items, it'll execute that number of times. This will cause the function to end up in a different working directory, which is causing the issue. These internal functions should be deterministic, Ideally, they should not change the working directory. and if they do, they should always revert to the original working directory where they were executed

2022-06-21 09:34 UTC, neelasha23 commented
Got it. I will need to go the parent directory of `dist` before start of every loop otherwise it fails. I will try to think of a way around.
What about the the issue with windows? Doesn't look like filenames can have `*` in them on Windows. So should I change the naming convention of the requirements.task-*.lock.txt files? Maybe have __ like Ido suggested?

2022-06-21 09:44 UTC, edublancas commented
yeah, I think double underscore makes sense, we already have something similar for the SLURM exporter: https://github.com/ploomber/soopervisor/blob/566d7773a3af408046d0efbdbd80ad10f77bb620/src/soopervisor/shell/export.py#L33

2022-06-21 18:46 UTC, neelasha23 commented
The CI is passing now for all the platforms. I have also submitted a pipeline to AWS batch and verified that the tasks are getting scheduled in the corresponding image. Had to use `args = ['docker', 'buildx', 'build', '--platform=linux/amd64', '.', '--tag', image_local]` for the jobs to run successfully.

2022-06-21 19:51 UTC, idomic commented on src/soopervisor/commons/dependencies.py
> +    if not _no_missing_dependencies('requirements', 'txt') \
I think we can simplify this by removing the nots and changing the condition to or

2022-06-21 20:03 UTC, idomic commented on tests/aws_batch/test_export.py
> +def test_export_multiple_images(mock_batch, monkeypatch,
Can we break this test into smaller tests? It'll ease CI debugging when stuff breaks. Also the initial mocks can be a fixture

2022-06-21 20:03 UTC, idomic requested changes
Added a few comments, I'll also try now running it and seeing how it works

2022-06-23 09:49 UTC, neelasha23 commented on tests/aws_batch/test_export.py
> +def test_export_multiple_images(mock_batch, monkeypatch,
Made the changes. If the fixtures look fine will add them to the existing testcases also

2022-06-23 09:50 UTC, neelasha23 commented
> @neelasha23 I ran it and looked on the code build for this user: 95de7987, with the sample pipeline - multiple_requirements_project. Where can I see the 2 images creation? I didn't see it in the build. Also, I saw the batch tasks are failing (sent you the links).

have sent you some links of job run in us-west-2 (that's where I set up AWS Batch initially). Let me know if I should repeat the same in prod

2022-06-27 14:57 UTC, idomic commented on tests/assets/multiple_requirements_project/requirements.lock.txt
> +numpy
@neelasha23 Can we make sure those dependencies are completely different between the tasks?

2022-06-28 15:31 UTC, neelasha23 commented
Have added `seaborn` dependency for the `plot` task in multiple_requirements_project in `test/assets`. While testing it i found a bug. The `docker build` command was installing dependencies from the `env` folder whereas the correct task specific file was present in the `/project` folder.  So i have created a `Dockerfile` specific to aws-batch : https://github.com/ploomber/soopervisor/blob/789f6087a8ec375c79ea97bc8037d8c38636513a/src/soopervisor/assets/aws-batch/Dockerfile and changed the sequence of instalment command to be after `RUN tar --strip-components=1 -zxvf *.tar.gz`.

2022-06-29 12:48 UTC, idomic commented
@neelasha23 Is it now batch-specific? Since it wasn't the initial intention.

2022-06-29 12:59 UTC, neelasha23 commented
No it's not aws batch specific. Since aws batch is the priority right now, I have only modified the Dockerfile  for the same. To be on the safe side I haven't modified the common `Dockerfile`. I did test with Argo and it seemed to be fine, but still once all the exporters are properly tested with this Dockerfile change maybe we can have just one Dockerfile.

2022-06-29 13:00 UTC, idomic commented
Got it! Let's finish testing on the rest of the backs, generalize this Dockerfile and merge

2022-06-29 13:10 UTC, idomic commented
@edublancas ?
I think it's residues from the run?

2022-06-29 13:20 UTC, idomic commented
@neelasha23 how much time do you think it'll take you including the rest of them?
@edublancas thoughts on including the rest of the backends in? If it's ~2-3 days extra dev work I think we should add it, there's no pressing deadline currently.

2022-06-29 13:24 UTC, neelasha23 commented
I had initially started with Airflow and Kubeflow. And i remember the environment was breaking. So would to figure those out first and then check the code changes. All the exporters have different logic for the export.

2022-06-30 04:25 UTC, neelasha23 commented
Sure. Any other reviews for this PR?

2022-06-30 13:01 UTC, merged