bundle custom lib in docker image
ploomber/soopervisor pull request #87
Opened 2022-06-24 18:25 UTC by Wxl19980214

## Describe your changes
Add path check. If Path(lib/') exist, add a PYTHONPATH in docerfile to look for packages under lib.

## Issue ticket number and link
Closes #85 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-06-27 13:41 UTC, edublancas commented
please write an automated test, see this for details: https://github.com/ploomber/soopervisor/issues/88

2022-06-27 13:41 UTC, Wxl19980214 commented
@edublancas  Yes. I have tested in this way. This is my project structure:
project/
          lib/ 
               package_a.py (contains function printTest() )
          fit.py  (from lib.package_a import printTest )
          ....

And I use sooperviosr add and export to build the image. It looks like there's no error when I run the image.

2022-06-27 15:39 UTC, idomic commented
@Wxl19980214 please add a few tests.

2022-06-27 17:04 UTC, Wxl19980214 commented
@edublancas  @idomic I am having troubling writing test: Here is what I have:
<pre>
@pytest.mark.parametrize('CLASS_', [
    AWSBatchExporter,
    AirflowExporter,
    ArgoWorkflowsExporter,
    KubeflowExporter,
],
                         ids=[
                             'batch',
                             'airflow',
                             'argo',
                             'kubeflow',
                         ])
def test_docker_local_lib_import(
    mock_docker_and_batch,
    tmp_sample_project,
    no_sys_modules_cache,
    skip_repo_validation,
    capsys,
    CLASS_,
):

    exporter = CLASS_.new(path_to_config='soopervisor.yaml', env_name='serve')

    exporter.add()
    exporter.export(mode='force', skip_tests=True)

    client = docker.from_env()
    client.containers.run('python', 'import package_a')
    
    captured = capsys.readouterr()

    print(captured.out)


</pre>

I have added the lib/ directory with package_a under asset/sample_project. However, it seems like the docker.from_env() is mocked so I cannot get real result. Any ideas?

2022-06-27 17:05 UTC, Wxl19980214 commented
Also for some reason, i cannot recreate what I had last week. After soopervisor export, what command do we use to run the image? docker run example:latest? I have tried and it looks like not working

2022-06-27 18:29 UTC, idomic commented
That's right. After the export command you should have the image tagged locally and you can simply use `docker run tag -it` to run it and debug. You can also list the available images to see if it's not there for some reason.

2022-06-27 18:37 UTC, idomic commented
It should be something like this `docker run image_name:tag_name`

On Mon, Jun 27, 2022 at 2:35 PM Xilin ***@***.***> wrote:

> Ok this is weird, I have checked I have images locally by docker images
>
> example $ docker images
> REPOSITORY TAG IMAGE ID CREATED SIZE
> example latest af4bedf7589c 2 hours ago 1.15GB
>
> but when I do: docker run example -it, it returns this:
> [FATAL tini (6)] exec -it failed: No such file or directory
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ploomber/soopervisor/pull/87#issuecomment-1167731477>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACYPJOJP35GOVK2U3PWQN2LVRHX5LANCNFSM5ZYUI6SA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-27 18:46 UTC, Wxl19980214 commented
docer run example:latest? 
It just returns nothing and not actually running the image.

2022-06-27 19:11 UTC, idomic commented
Issue solved.

2022-06-27 20:43 UTC, Wxl19980214 commented
@edublancas I think he meant local test are done. I am still figuring out a way to write automated tests.

2022-06-27 20:44 UTC, edublancas commented
ok cool

2022-06-28 19:32 UTC, edublancas requested changes

2022-06-28 19:32 UTC, edublancas commented on tests/test_export.py
> +    exporter.add()
I see what you mentioned. this line always overwrites soopervisor.yaml

try something like this:

```python

exporter.add()

# load soopervisor.yaml using the yaml library

# set repository to null

exporter.export(mode='incremental', skip_tests=True)
```

2022-06-28 21:30 UTC, edublancas requested changes
can you add a section here: https://github.com/ploomber/soopervisor/blob/master/doc/user-guide/build-process.rst

explaining how this new feature works?

2022-06-28 21:30 UTC, edublancas commented on tests/environment.yml
> +- pip: 1
what is this file for?

2022-06-29 19:33 UTC, edublancas commented
is this ready for review?

2022-06-29 19:39 UTC, Wxl19980214 commented
@edublancas Yes. I couldn't find where the changes were requested. I thought I resolved them all.

2022-06-29 20:11 UTC, idomic commented
@Wxl19980214 Did you do some manual tests as well?

2022-06-29 20:13 UTC, Wxl19980214 commented
@idomic Yes I have tried with argo and kubernate. I can go ahead and check other backend as well

2022-06-29 20:14 UTC, merged

2022-06-29 20:14 UTC, idomic commented
Please test from main with another backend let's say batch

2022-06-29 20:43 UTC, Wxl19980214 commented
Just tested. There is no issue.